version: "3.0"

volumes:
  vol-postgres:

services:
  postgresql:
    container_name: postgresql-server
    image: postgres:12.0
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - 5432:5432
    networks:
      - postgres_network

  pgadmin:
    container_name: pgadmin-server
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=ricardo.soares.sarto@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=postgres'
      - 'PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True'
      - 'PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"'
      - 'PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10'
    networks:
      - postgres_network

networks:
  postgres_network: